go_import_path: github.com/cafebazaar/blacksmith

language: go

sudo: required

services:
  - docker

go:
  - 1.7
  - tip

before_install:
- make dependencies
- make run_test_etcd

script: make test

matrix:
  allow_failures:
    - go: tip
